name: expenzio
description: An Control Expanses App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-112.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  micro_core:
    git:
      url: https://github.com/guilhermebernava/micro_core.git
      ref: main
    version: ^0.0.2
  common:
    path: packages/commons/common

  #micro_apps
  login:
    path: packages/micro_apps/login

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - packages/micro_apps/login/assets/
    - assets/images/
