name: expanses_app
description: An Control Expanses App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-112.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  micro_core:
    git:
      url: https://github.com/guilhermebernava/micro_core.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
