name: splash
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  micro_core:
    git:
      url: https://github.com/guilhermebernava/micro_core.git
      ref: main

  common_dependencies:
    path: ../../commons/common_dependencies
  common:
    path: ../../commons/common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
