name: common_dependencies
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  get_it: ^7.6.0
  bloc_test: ^9.1.1
  lottie: ^2.3.2

  google_sign_in: ^6.1.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1

  connectivity_plus: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.0.2
  micro_core:
    git:
      url: https://github.com/guilhermebernava/micro_core.git
      ref: main
    version: ^0.0.2
  common:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
